// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "slave_services.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::slave;

class slave_servicesHandler : virtual public slave_servicesIf {
 public:
  slave_servicesHandler() {
    // Your initialization goes here
  }

  void ActiveStoreTransfer(StorRetVal& _return, const ActiveParams& p, const int32_t iflags) {
    // Your implementation goes here
    printf("ActiveStoreTransfer\n");
  }

  void PasvStoreTransfer(StorRetVal& _return, const PasvParams& p, const int32_t iflags) {
    // Your implementation goes here
    printf("PasvStoreTransfer\n");
  }

  void ActiveRetrieveTransfer(std::string& _return, const ActiveParams& p) {
    // Your implementation goes here
    printf("ActiveRetrieveTransfer\n");
  }

  void PasvRetrieveTransfer(std::string& _return, const PasvParams& p) {
    // Your implementation goes here
    printf("PasvRetrieveTransfer\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<slave_servicesHandler> handler(new slave_servicesHandler());
  shared_ptr<TProcessor> processor(new slave_servicesProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

