// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "SlaveServices.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::slave;

class SlaveServicesHandler : virtual public SlaveServicesIf {
 public:
  SlaveServicesHandler() {
    // Your initialization goes here
  }

  bool ActiveStoreTransfer(const std::string& ip, const int16_t port, const int64_t fid, const int64_t start_at) {
    // Your implementation goes here
    printf("ActiveStoreTransfer\n");
  }

  bool PasvStoreTransfer(const std::string& ip, const int16_t port, const int64_t fid, const int64_t start_at) {
    // Your implementation goes here
    printf("PasvStoreTransfer\n");
  }

  bool ActiveRetrieveTransfer(const std::string& ip, const int16_t port, const int64_t fid, const int64_t start_at) {
    // Your implementation goes here
    printf("ActiveRetrieveTransfer\n");
  }

  bool PasvRetrieveTransfer(const std::string& ip, const int16_t port, const int64_t fid, const int64_t start_at) {
    // Your implementation goes here
    printf("PasvRetrieveTransfer\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<SlaveServicesHandler> handler(new SlaveServicesHandler());
  shared_ptr<TProcessor> processor(new SlaveServicesProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

