/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "slave_services_constants.h"

namespace slave {

const slave_servicesConstants g_slave_services_constants;

slave_servicesConstants::slave_servicesConstants() {
}

} // namespace

