/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef slave_services_CONSTANTS_H
#define slave_services_CONSTANTS_H

#include "slave_services_types.h"

namespace slave {

class slave_servicesConstants {
 public:
  slave_servicesConstants();

};

extern const slave_servicesConstants g_slave_services_constants;

} // namespace

#endif
